import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import path from 'path';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                //js
                "resources/js/app.js",
                "resources/js/config.js",
                "resources/js/pages/dashboard.js",
                "resources/js/pages/calendar.js",
                "resources/js/pages/auth-two-factor.js",
                "resources/js/pages/auth-password.js",
                "resources/js/pages/chart-area.js",
                "resources/js/pages/chart-other.js",
                "resources/js/pages/chart-bar.js",
                "resources/js/pages/chart-line.js",
                "resources/js/pages/form-fileupload.js",
                "resources/js/pages/form-typehead.js",
                "resources/js/pages/form-choice.js",
                "resources/js/pages/form-quilljs.js",
                "resources/js/pages/form-wizard.js",
                "resources/js/maps/leaflet-data.js",
                "resources/js/pages/maps-leaflet.js",
                "resources/js/maps/world-merc.js",
                "resources/js/maps/world.js",
                "resources/js/maps/in-mill-en.js",
                "resources/js/maps/canada.js",
                "resources/js/maps/iraq.js",
                "resources/js/maps/russia.js",
                "resources/js/maps/spain.js",
                "resources/js/maps/us-aea-en.js",
                "resources/js/maps/us-lcc-en.js",
                "resources/js/maps/us-mill-en.js",
                "resources/js/pages/maps-vector.js",
                "resources/js/pages/datatables-ajax.js",
                "resources/js/pages/datatables-basic.js",
                "resources/js/pages/datatables-child-rows.js",
                "resources/js/pages/datatables-checkbox-select.js",
                "resources/js/pages/datatables-show-hide-columns.js",
                "resources/js/pages/datatables-export-data.js",
                "resources/js/pages/datatables-rendering.js",
                "resources/js/pages/flags-listing.js",
                "resources/js/pages/datatables-javascript-source.js",
                "resources/js/pages/datatables-select.js",
                "resources/js/pages/ui-interactive.js",
                "resources/js/pages/content-management/articles/article.js",
                "resources/js/pages/content-management/articles/article-create.js",
                "resources/js/pages/content-management/articles/article-edit.js",
                "resources/js/pages/content-management/products/product.js",
                "resources/js/pages/content-management/products/product-create.js",
                "resources/js/pages/content-management/products/product-edit.js",
                "resources/js/pages/content-management/faq.js",
                "resources/js/pages/content-management/tag.js",
                "resources/js/pages/content-management/testimonial.js",
                "resources/js/pages/customers/customer.js",
                "resources/js/pages/credit-simulations/credit-simulation.js",
                "resources/js/pages/credit-simulations/installment.js",
                "resources/js/pages/submissions/submission.js",
                "resources/js/pages/users/user.js",

                //css
                "resources/scss/app.scss",
                "node_modules/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css",
                "node_modules/datatables.net-select-bs5/css/select.bootstrap5.min.css",
                "node_modules/datatables.net-bs5/css/dataTables.bootstrap5.min.css",
                "node_modules/dropzone/dist/dropzone.css",
                "node_modules/quill/dist/quill.bubble.css",
                "node_modules/quill/dist/quill.core.css",
                "node_modules/quill/dist/quill.snow.css",
                "node_modules/leaflet/dist/leaflet.css",
                "node_modules/jsvectormap/dist/jsvectormap.min.css",

                // Frontend Landing Page Assets (new)
                'resources/scss/frontend.scss',
                'resources/js/frontend.js',
            ],
            refresh: true,
        }),
    ],
});
